# Generated by Django 5.2.12 on 2026-03-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('modality', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('multimodal', 'Multimodal')], max_length=20)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('BLOCKED', 'Blocked')], max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
                ('avg_confidence', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'modality', 'status')},
            },
        ),
    ]
