# Generated by Django 5.2.12 on 2026-03-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationlog',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='severity_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
