MODERATION_STATUS_APPROVED = 'APPROVED'
MODERATION_STATUS_FLAGGED  = 'FLAGGED'
MODERATION_STATUS_BLOCKED  = 'BLOCKED'

MODALITY_TEXT       = 'text'
MODALITY_IMAGE      = 'image'
MODALITY_VIDEO      = 'video'
MODALITY_MULTIMODAL = 'multimodal'

SEVERITY_LOW      = 'LOW'
SEVERITY_MEDIUM   = 'MEDIUM'
SEVERITY_HIGH     = 'HIGH'
SEVERITY_CRITICAL = 'CRITICAL'
